work_dir: ./work_dir/Hyperf_2_noYolo

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: ../Processed_data/FTVD.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: ../Processed_data/FTVD.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.Hyperformer_2_noYolo.Model
model_args:
  num_class: 10
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  joint_label: [0, 4, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 3, 3, 3, 2, 3, 3, 3, 1, 0, 1, 0, 1]

#optim
weight_decay: 0.0004
base_lr: 0.01  # MODIFIED: originally 0.01 (results2590873.txt)
lr_decay_rate: 0.1 # MODIFIED: originally 0.1 (results2590873.txt)
#step: [35, 55]
step: [110, 120]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64         # MODIFIED: originally 64
test_batch_size: 128    # MODIFIED: originally 128
num_epoch: 2  # MODIFIED: originally 50
nesterov: True

